### ISSUE TITLE
Does not work with React 16

### ISSUE THREAD

**Issue by govindrai** [borisyankov/react-sparklines#95]
Accessing PropTypes via the main React package is deprecated, and has been removed in React v16.0. The library crashes the app immediately with proptype errors.

This is not specified in the docs and should be one of the first things specified. And please upgrade the library :)

Had to downgrade react and reactdom and sparklines (sparklines 1.7.0 is broken too). 

Here are the versions where things work correctly:

```
"dependencies": {
    ...
    "react": "^15.0.0",
    "react-dom": "^15.0.0",
    "react-sparklines": "^1.5.0",
    ...
}
```

**Comment by iabw** [comment]
It looks to me like it's already using the separate prop-types package everywhere, [since July](https://github.com/borisyankov/react-sparklines/commit/e3add809067416cffeaa7f119f0c9eec1d3fdfa8#diff-e4f8148ed0dada8d9354b418e49286ff).

I upgraded to React 16 with only a minor hiccup in Barcharts disappearing if they were too narrow.

I'm on version 1.7.0 of Sparklines.

**Comment by govindrai** [comment]
@iabw you're absolutely right. Everything works well on the latest versions. It's just that I had used the 1.6.0 version when it was released which had a bug and I resorted to using version 1.5.0. 

1.7.0 works well with React 16. I will close this.

**Comment by govindrai** [comment]
@iabw you're absolutely right. Everything works well on the latest versions. It's just that I had used the 1.6.0 version when it was released which had a bug and I resorted to using version 1.5.0. 

1.7.0 works well with React 16. I will close this.
